# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('iadd-routing-protocol', ['core','network','internet','mobility','netanim'])
    module.source = [
        'model/iadd-routing-protocol.cc',
        'helper/iadd-routing-protocol-helper.cc',
        'model/DataCache.cc',
        'model/GPS.cc',
        'model/IADDTypeHeader.cc',
        'model/NeighborList.cc',
        'model/PendingPackets.cc',
        'model/Segment.cc',
        'model/Vehicle.cc',
        'model/IADDPacketTracer.cc'
        ]

    module_test = bld.create_ns3_module_test_library('iadd-routing-protocol')
    module_test.source = [
        'test/iadd-routing-protocol-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'iadd-routing-protocol'
    headers.source = [
        'model/iadd-routing-protocol.h',
        'helper/iadd-routing-protocol-helper.h',
               'model/DataCache.h',
        'model/GPS.h',
        'model/IADDTypeHeader.h',
        'model/NeighborList.h',
        'model/PendingPackets.h',
        'model/Segment.h',
        'model/Vehicle.h',
        'model/constants.h',
        'model/IADDPacketTracer.h'
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

