# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('iadd-routing-protocol-example', ['iadd-routing-protocol'])
    obj.source = 'iadd-routing-protocol-example.cc'

