# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('iadd-requester-app-example', ['iadd-requester-app'])
    obj.source = 'iadd-requester-app-example.cc'

