# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('iadd-requester-app', ['internet','mobility','iadd-routing-protocol'])
    module.source = [
        'model/iadd-requester-app.cc',
        'helper/iadd-requester-app-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('iadd-requester-app')
    module_test.source = [
        'test/iadd-requester-app-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'iadd-requester-app'
    headers.source = [
        'model/iadd-requester-app.h',
        'helper/iadd-requester-app-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

